<?php

namespace NP\Bundle\SitemakerBundle\Entity;

use Doctrine\ORM\EntityRepository;
use NP\Bundle\SitemakerBundle\Entity\Site;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
}
