<?php

namespace NP\Bundle\SitemakerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SitemapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitemapRepository extends EntityRepository
{
}
